# Generated by Django 4.2.30 on 2026-08-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_note_options_alter_note_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='study_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_notes', to='study.studygoal'),
        ),
        migrations.AlterField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='study.topic'),
        ),
    ]
